### ISSUE TITLE
how to maintain the connection (Ping-pong/heartbeat)

### ISSUE THREAD

**Issue by JoyX2** [M1ngXU/Socket.IO-Unity#1]
How to keep the client connected ?
I'm using KyleDulce.SocketIo but it sadly got depreciated, and as soon as I developed deep enough I realized that there is no ping-pong/heartbeeat mechanism, so all clients would disconnected as soon as the time ran out.

could you show me an example to maintain a heart beat ?
I'm using python as the backenet/server, would that be a problem ?

**Comment by M1ngXU** [comment]
Socket.io is based on engine.io - the pinging is done via engine.io
here is the c# code
https://github.com/M1ngXU/Socket.IO-Unity/blob/499fb12fc286c121d05d5f44240d7e503829ca37/Script/Socket.cs#L42

python shouldn't cause any issues
