### ISSUE TITLE
NullReferenceException SocketIOUnity.cs:32

### ISSUE THREAD

**Issue by JoyX2** [M1ngXU/Socket.IO-Unity#3]
hi, 
this is a new scene on unity 2019.4.36f1
![image](https://user-images.githubusercontent.com/101886922/166552228-4bdaf65b-9bb8-4043-af6f-cb8d375aaba7.png)

I have 2 scripts on 1 object ( I disabled mine so 1 script on 1 empty object and the error was still generated )

I believe the error is referring to this line 

![image](https://user-images.githubusercontent.com/101886922/166553055-9859ebb7-8ccd-4edf-9d5b-68dc409329bc.png)
which is enum if i'm not wrong and it has been already defined as "Closed" it even says that on the inspector 

![image](https://user-images.githubusercontent.com/101886922/166553270-61de2fc2-aa55-4c69-a0fc-bc864ca011e9.png)

Not sure why it says null

**Comment by JoyX2** [comment]
I've added those 3 lines to see what is being null
![image](https://user-images.githubusercontent.com/101886922/166555222-25bc2546-4730-4a98-8474-cd165a9a07bb.png)

and here is the result, which kinda make sense 

![image](https://user-images.githubusercontent.com/101886922/166555365-5508c13f-dc75-425f-819d-8797007dccc6.png)


socket hasn't been defined , what is the right way to define socket ?

![image](https://user-images.githubusercontent.com/101886922/166555504-8d908109-9776-47f1-b4aa-22fd7cf773cc.png)

that is the only mention of it before the "Update()"
it was null, not sure which function is supposed to define it.

**Comment by JoyX2** [comment]
add the following line of code before anything else in the update function, solved it for me.
```
 if (Socket == null) return;
 ```
cheers

**Comment by M1ngXU** [comment]
looking at the readme-example (https://github.com/M1ngXU/Socket.IO-Unity/blob/master/README.md) - i think you need to have the SocketIOUnity.cs on your object. If you want to use these scripts, make sure to
1) implement binary transfers if needed
2) check if acks work (didn't test it well)
