### ISSUE TITLE
change the SocketState on connection drop

### ISSUE THREAD

**Issue by frescogusto** [M1ngXU/Socket.IO-Unity#4]
when the server closes the connection I get this error

`WebSocketException: The remote party closed the WebSocket connection without completing the close handshake.`

but the SocketState remains Open
it would be ideal to Dispose() the connection when getting this specific error, is there a way?

**Comment by M1ngXU** [comment]
what line is the error in?

**Comment by frescogusto** [comment]
it throws in the ReceiveInBackground() function, Socket.cs, line 214

https://github.com/M1ngXU/Socket.IO-Unity/blob/8d2d41dd8b671c8d307149cafe0ccd51bac56536/Script/Socket.cs#L214

**Comment by M1ngXU** [comment]
I currently cannot test it, but a `try-catch` should do it.

you can just put the whole method body into a try block, and catch any exception. in the catch branch you can then change the state or do anything else.

**Comment by frescogusto** [comment]
is there a way to know if the socket is connected or disconnected?

**Comment by M1ngXU** [comment]
yes, though it's not as trivial as one might think: https://stackoverflow.com/questions/2661764/
