### ISSUE TITLE
How to disconnect ?

### ISSUE THREAD

**Issue by JoyX2** [M1ngXU/Socket.IO-Unity#5]
I know this is how we connect 
```
_ = socket.Connect("ws://192.168.178.44:3000");
socket.On("connect", s => Debug.Log(":)"));
```

But how as a client to close the connection ? , I cant find socket.Disconnect(); 
Is there is a way for the server to force disconnect a client or a client to voluntarily leave the server ?

**Comment by M1ngXU** [comment]
Currently not possible, but you could make `Socket` public inside [SocketIOUnity](https://github.com/M1ngXU/Socket.IO-Unity/blob/8d2d41dd8b671c8d307149cafe0ccd51bac56536/Script/SocketIOUnity.cs#L15) and then shutdown the socket with that.

**Comment by JoyX2** [comment]
> Currently not possible, but you could make `Socket` public inside [SocketIOUnity](https://github.com/M1ngXU/Socket.IO-Unity/blob/8d2d41dd8b671c8d307149cafe0ccd51bac56536/Script/SocketIOUnity.cs#L15) and then shutdown the socket with that.


I've made `SocketIOUnity.Socket` public 
to shutdown the connection all I have to do is to call `Socket.Dispose();` ?
**like:** 
`SocketIOUnity.Socket soc;`
`soc.Dispose(); ?`

**Comment by M1ngXU** [comment]
> I've made `SocketIOUnity.Socket` public

that's what I've meant 😅


> to shutdown the connection all I have to do is to call `Socket.Dispose();` ?

No, you should call shutdown (unless you don't need a graceful shutdown)

**Comment by JoyX2** [comment]
> > I've made `SocketIOUnity.Socket` public
> 
> that's what I've meant 😅
> 
> > to shutdown the connection all I have to do is to call `Socket.Dispose();` ?
> 
> No, you should call shutdown (unless you don't need a graceful shutdown)

![image](https://user-images.githubusercontent.com/101886922/206863815-169a386b-0a0b-482e-8b35-e55f58952ab6.png)

_* there is also 1 more option hidden on the drop down list `toString()` which is not useful at all in our case._

There is no `shutdown()` for `SocketIOUnity` nor for `SocketIOUnity.Socket`, could you give me a code example of what you mean ?

on the other hand, `Socket.Dispose();` does work but it also outputs an error every time I use it.

**Comment by M1ngXU** [comment]
hmm, the `SocketIOUnity.Socket` is actually my own wrapper around a builtin wrapper 😅. Calling dispose should be correct, or you can also add a shutdown method that is the same as the dispose method but calls shutdown instead.

What error do you get?

**Comment by JoyX2** [comment]
> hmm, the `SocketIOUnity.Socket` is actually my own wrapper around a builtin wrapper 😅. Calling dispose should be correct, or you can also add a shutdown method that is the same as the dispose method but calls shutdown instead.
> 
> What error do you get?

Yeah I have noticed that it was your wrapper lol
here is the error that comes after calling `dispose()`

`SocketException: The I/O operation has been aborted because of either a thread exit or an application request.`

`Rethrow as IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.`

about the **shutdown** method:
I cant find any reference to it in the package, could you walk me throw it or maybe add a quick update ?

**Comment by M1ngXU** [comment]
what lines are the errors in?

shutdown: https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.shutdown?view=net-6.0

**Comment by JoyX2** [comment]
> what lines are the errors in?
> 
> shutdown: https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.shutdown?view=net-6.0

It doesnt say which line, I think it's referring to the on going connection between the server and the client got unexpectedly  interrupted 

I also couldnt find a mention of shutdown in the package , the results for the search process for `shutdown` in the whole package was `0 matches` , I believe it was not included in the package.

**Comment by M1ngXU** [comment]
the shutdown method should be "built-in" in the net package of c#.
Take a look here: https://github.com/M1ngXU/Socket.IO-Unity/blob/8d2d41dd8b671c8d307149cafe0ccd51bac56536/Script/Socket.cs#L21
this should be the "real" socket (bad naming uh). just put this public as well and then call the socket methods on that object.
